// <auto-generated />
namespace Shortly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class isQR_in_stats_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isQR_in_stats_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202312100352449_isQR_in_stats_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
