// <auto-generated />
namespace Shortly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_backhalf_to_urlmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_backhalf_to_urlmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "202312080509213_add_backhalf_to_urlmodels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
