// <auto-generated />
namespace Shortly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_required_from_user_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_required_from_user_id));
        
        string IMigrationMetadata.Id
        {
            get { return "202312080521113_remove_required_from_user_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
